# landscape short name
landscapeName: lfn
# Update with your membership structure
landscapeMemberClasses:
   - name: Platinum Membership
     category: Platinum
   - name: Gold Membership
     category: Gold
   - name: Silver Membership
     category: Silver
    - name: Associate Membership
     category: Associate
# SF Project record ID for your project
project: a094100000aErheAAC # LFN project
# Name of category for members 
landscapeMemberCategory: Linux Foundaton Networking
